### ISSUE TITLE
Error: Command terminated by signal 11

### ISSUE THREAD

**Issue by ay-amityadav** [yhg926/public_kssd#10]
Hi,

I'm trying to measure containment of a single genome in metagenomes, using `combined_metagenomics_65265_succed_sketches` provided with the manuscript `Kssd: sequence dimensionality reduction by k-mer substring space sampling enables real-time large-scale datasets analysis, 2021`. 

First, I sketch an e.coli genome successfully using command:
`./kssd_version1.0/kssd dist -L L3K10.shuf -r ./e-coli.fna -o e-coli_sketch`
 
 Next,  to compute distance between e-coli genome and metagenomes, I run the below command:
`./kssd_version1.0/kssd dist  -r ./e-coli_sketch/ref -o ./e-coli2metagenomes ./combined_metagenomics_65265_succed_sketches`
But it terminates with an **error** message, here is complete output from the command:
`run mco_cbd_koc_dist(), 754.560135G memory used	96 threads used
disf_sz=261008	refnum=1	qrynum=65252	num_mapping_distf=0bnum_infile=65252		261008	0	flag1:Ok
Command terminated by signal 11`

The above error is also produced with `kssd_version1.1` , and with other input genomes I tried. To reproduce the error, I'm attaching `e-coli.fna` as `e-coli.txt`.

However, when I search this e.coli genome against two of the sketches (provided with the manuscript) - `shakya` and `64constitute` then the commands complete successfully. The two commands ran are:
- `./kssd_version1.0/kssd dist -r ./e-coli_sketch/ref -o ./e-coli_genome2shakya  ./Sketches/shakya_qry/`
- `./kssd_version1.0/kssd dist -r ./e-coli_sketch/ref -o ./e-coli_genome264constitutes  ./Sketches/64constitute_qry/`

Many thanks
Amit
[e-coli.txt](https://github.com/yhg926/public_kssd/files/7299674/e-coli.txt)

**Comment by yhg926** [comment]
It seems like a memory problem, the memory usage is unusually high, how many memory allowed in your machine?  Kssd never consumed such high memory in my machine, may be the threads is too many? try specify less threads using -p. e.g. -p 12

**Comment by ay-amityadav** [comment]
Thanks a lot for your quick reply! The maximum memory allowed in my system is 755GB. I tried both with reduced memory using `-m` option and reduced no of threads using `-p` option but it didn't work. The exact combinations I tried are:  `-p 12`, `-m 30 -p 12` and `-m 10 -p 12`. The same error occurs on a different machine too.

**Comment by yhg926** [comment]
I have reproduced your error, I guess the file might have been damaged during uploading to google drive. The original copy is hard to find now. You can try re-download the metagenomics raw data from NCBI using the pipecmd function in kssd.

**Comment by ay-amityadav** [comment]
It's fine, I'll try downloading the raw data. Thank you very much for your time.
