### ISSUE TITLE
sketching individual sequences

### ISSUE THREAD

**Issue by Askarbek-orakov** [yhg926/public_kssd#4]
Hi, thanks for kssd!

It would be much more convenient if `kssd dist` had an option to sketch individual sequences within one sequence file. Like `-i` option in `mash screen`. 
```
-i         Sketch individual sequences, rather than whole files, e.g. for
             multi-fastas of single-chromosome genomes or pair-wise gene
             comparisons.
```

Thanks,

Askarbek

**Comment by yhg926** [comment]
Thanks for your suggestions, we will add this functionality in the next version.
