### ISSUE TITLE
Output description

### ISSUE THREAD

**Issue by Askarbek-orakov** [yhg926/public_kssd#5]
Hi,

Could you please add some more details on meaning of columns in the output files? For example, what exactly does "Shared_k|Ref_s|Qry_s" mean?

Thank you,

Askarbek

**Comment by yhg926** [comment]
Shared_k: Number of K-mers shared between the sketches of the reference and query;  
Ref_s:  Number of K-mers of the sketches of the reference
Qry_s:  Number of K-mers of the sketches of the query

**Comment by yhg926** [comment]
And the explanation for all the columns has been included in README.md

**Comment by Askarbek-orakov** [comment]
Thanks!
