### ISSUE TITLE
Shared_k meaning

### ISSUE THREAD

**Issue by Askarbek-orakov** [yhg926/public_kssd#6]
Hi,

You previously defined Shared_k as a number of K-mers shared between the sketches of the reference and query. What does it mean when the values are like 8-0 or 9-1? What does each of these two values mean?  

Thanks,

Askarbek

**Comment by yhg926** [comment]
Good question. for a-b, a are the total k-met sharing , b are the estimated k-mer sharing by random string combinations. b is usually very small thus not affect the value much. a-b try to adjust for the real k-mer sharing , but if it improves distance estimation has not been fully test yet.

**Comment by yhg926** [comment]
Good question. for a-b, a are the total k-met sharing , b are the estimated k-mer sharing by random string combinations. b is usually very small thus not affect the value much. a-b try to adjust for the real k-mer sharing , but if it improves distance estimation has not been fully test yet.
