### ISSUE TITLE
Context space is too crowd

### ISSUE THREAD

**Issue by dacheampong** [yhg926/public_kssd#7]
Have this error when sketching my query which is a single assembled metagenomic file, Changed the kmer length I used to sketch the reference to 9 but still get the same error.
Error message:
_"kssd: the context space is too crowd, try rerun the program using -k9: No such file or directory"_

Command: 
kssd dist -L reference/default.shuf -o query /storage/ont.fasta.gz

**Comment by yhg926** [comment]
By default, context space (or k-mer substring space) size  is partially determined by k-mer length. For metagenomic or mammal size genome dataset, I suggested use -k10 or -k11.

**Comment by dacheampong** [comment]
Thanks for the quick response, much appreciated, problem resolved after using a larger k-mer size >= 10.
